### PR TITLE
Remove redundant type defs and complete notebook-types refactor

### LINKED ISSUE #567: Duplicate `ObType` and `MorType` exported in catlog_wasm.d.ts
When I run `pnpm run build` and look at `packages/catlog-wasm/pkg/catlog_wasm.d.ts`, there are two exports for `ObType` (lines 31 and 71), which are identical:

```{typescript}
/**
 * Object type in a double theory.
 */
export type ObType = { tag: "Basic"; content: Ustr } | { tag: "Tabulator"; content: MorType };
```

However, there are two *non-identical* exports for `MorType` (lines 36 and 66), with the latter not including the `Composite` tag type:

```{typescript}
/**
 * Morphism type in a double theory.
 */
export type MorType = { tag: "Basic"; content: Ustr } | { tag: "Composite"; content: MorType[] } | { tag: "Hom"; content: ObType };

...

/**
 * Morphism type in a double theory.
 */
export type MorType = { tag: "Basic"; content: Ustr } | { tag: "Hom"; content: ObType };
```

This is causing issues in the ECLD branch, because we use `Composite`, and it seems like the latter declaration overwrites the former, which results in the following browser console error when trying to actually create one of these composite morphisms:

```
Error: Error: unknown variant `Composite`, expected `Basic` or `Hom`
```

---

I *think* the problem comes from the fact that both `packages/catlog-wasm/src/theory.rs` and `packages/notebook-types/src/v0/theory.rs` define a `MorType`, and the latter only includes `Basic` and `Hom`.

### PR DESCRIPTION
**Pull request by epatters**
Closes #567. This was more work than I expected since it turns out that #473 hadn't finished refactoring `ObType` and `MorType` to use the quoting and elaboration traits.

### CODE REVIEW

File: packages/catlog-wasm/src/model.rs [hunk 1]
```diff
@@ -235,25 +193,6 @@ impl CanQuote<Path<TabOb<Uuid, Uuid>, TabEdge<Uuid, Uuid>>, Mor> for Quoter {
...
-            Mor::Composite(Box::new(demote_path(path.clone().map(Ob::Basic, Mor::Basic))))
-        }
-    }
-}
-
-impl CanQuote<Path<Ustr, Ustr>, MorType> for Quoter {
-    fn quote(&self, path: &Path<Ustr, Ustr>) -> MorType {
-        match path {
-            Path::Id(u) => MorType::Hom(Box::new(ObType::Basic(*u))),
-            Path::Seq(non_empty) => MorType::Basic(non_empty[0]),
```
Comment (epatters) [inline packages/catlog-wasm/src/model.rs:252]: This was also a bug.
