### PR TITLE
Factor linear/Lotka-Voltera ODE analyses through `PolynomialSystem`

### LINKED ISSUE #965: Factor linear/Lotka-Voltera ODE analyses through `PolynomialSystem`
Most of the existing ODE simulation analyses are mathematically based on polynomial vector fields; the only exception is the experimental Kuramoto system. However, for historical reasons, only the mass action analysis was implemented using the `PolynomialSystem` data structure.

The hard-coded vector fields for the linear and Lotka-Volterra ODE analyses should be removed and replaced with code that generates suitable `PolynomialSystem`s (linear in one case, quadratic in the other).

An immediate advantage to having a symbolic representation is that we can use @kasbah's new LaTeX pretty-printer (#954) to display the systems of equations for these analyses.

### PR DESCRIPTION
**Pull request by georgefst**
Closes #965.

Developed alongside @patrickaldis.

### CODE REVIEW

File: packages/catlog/src/stdlib/analyses/ode/linear_ode.rs [hunk 1]
```diff
@@ -47,7 +47,7 @@ impl SignedCoefficientBuilder<QualifiedName, QualifiedPath> {
         &self,
         model: &DiscreteDblModel,
         data: LinearODEProblemData,
-    ) -> ODEAnalysis<LinearODESystem> {
+    ) -> ODEAnalysis<NumericalPolynomialSystem<u8>> {
```
Comment (georgefst) [inline packages/catlog/src/stdlib/analyses/ode/linear_ode.rs:86]: The exponent for linear systems is obviously always 1. So it's tempting to use or define a singleton type, but that might be overkill. Not sure how easy or conventional it is in Rust.

File: packages/catlog/src/zero/alg.rs [hunk 2]
```diff
@@ -183,6 +183,29 @@ where
 // XXX: Lots of boilerplate to delegate the module structure of `Polynomial` to
 // `Combination` because these traits cannot be derived automatically.
 
+impl<Var, Coef, Exp> Sum for Polynomial<Var, Coef, Exp>
```
Comment (georgefst) [inline packages/catlog/src/zero/alg.rs:186]: There's nothing here that's actually specific to `Polynomial`. The exact same code could be used for any `AdditiveMonoid`. But I don't think Rust allows instances with that sort of flexibility. We could define some reusable helper, but probably not worth it.

Note that `Polynomial` is an `AdditiveMonoid` precisely when its coefficient type is, due to the instances:
- `impl<Var, Coef, Exp> Add for Polynomial<Var, Coef, Exp>`
- `impl<Var, Coef, Exp> Zero for Polynomial<Var, Coef, Exp>`

Comment (georgefst) [reply packages/catlog/src/zero/alg.rs:186]: Oh, and also, looking at the comment above this, maybe we should actually move the main `Impl` code to `Combination`, and just delegate to that here?

File: packages/catlog/src/zero/alg.rs [hunk 3]
```diff
@@ -210,7 +233,7 @@ where
 impl<Var, Coef, Exp> Zero for Polynomial<Var, Coef, Exp>
 where
     Var: Ord,
-    Coef: Add<Output = Coef> + Zero,
+    Coef: Zero,
```
Comment (georgefst) [inline packages/catlog/src/zero/alg.rs:237]: This slight generalisation was useful during debugging. I'm not sure if it was necessary in the end, but there's no harm.

Coming from Haskell, I am a bit surprised that the compiler doesn't warn about redundant constraints.

File: packages/catlog/src/stdlib/analyses/ode/linear_ode.rs (hunk 1 above)
Comment (patrickaldis) [reply packages/catlog/src/stdlib/analyses/ode/linear_ode.rs:86]: I'm not sure this accounts for constants (zero exponents) though. We'd need a type with 0 and 1

Comment (georgefst) [reply packages/catlog/src/stdlib/analyses/ode/linear_ode.rs:86]: Oh yeah, good point 🤦‍♂️

File: packages/catlog/src/zero/alg.rs (hunk 3 above)
Comment (epatters) [reply packages/catlog/src/zero/alg.rs:237]: Yeah, I've found myself wishing for such warnings but AFAIK, the Rust compiler doesn't warn about either redundant constraints or unnecessary constraints.

File: packages/catlog/src/simulate/ode/lotka_volterra.rs [hunk 4]
```diff
@@ -1,45 +1,45 @@
...
-    fn vector_field(&self, dx: &mut DVector<f32>, x: &DVector<f32>, _t: f32) {
-        let A = &self.interaction_coeffs;
-        let b = &self.growth_rates;
-        *dx = (A * x + b).component_mul(x);
+) -> NumericalPolynomialSystem<u8> {
+    NumericalPolynomialSystem {
+        components: interaction_coeffs
+            .row_iter()
+            .enumerate()
+            .zip(growth_rates.into_iter())
```
Comment (epatters) [inline packages/catlog/src/simulate/ode/lotka_volterra.rs]: To avoid triggering the linter in CI, you can run `cargo clippy` locally before pushing.

Comment (georgefst) [reply packages/catlog/src/simulate/ode/lotka_volterra.rs]: Thanks. Done.

**Comment by georgefst** [comment]
> I'd suggest the following alternative design

In the last commit, we've refactored so that polynomials with symbolic coefficients are created first, and added some LaTeX tests to exercise the symbolic versions.

Hopefully this is roughly what you had in mind. If so, we'll then proceed with a similar change for the Lotka-Volterra systems.

File: packages/catlog/src/stdlib/analyses/ode/linear_ode.rs (hunk 1 above)
Comment (georgefst) [reply packages/catlog/src/stdlib/analyses/ode/linear_ode.rs:86]: We could of course define a zero-or-one type instead. But still, probably overkill.

File: packages/catlog/src/stdlib/analyses/ode/linear_ode.rs [hunk 5]
```diff
@@ -4,8 +4,11 @@
 //! [`linear_ode_analysis`](SignedCoefficientBuilder::linear_ode_analysis).
```
Comment (georgefst) [inline packages/catlog/src/stdlib/analyses/ode/linear_ode.rs:4]: Ah, I suppose this is no longer true now that this module also contains the new generalised `linear_polynomial_system` as well.

File: packages/catlog/src/stdlib/analyses/ode/linear_ode.rs [hunk 6]
```diff
@@ -92,10 +134,98 @@ mod test {
...
+        let expected = expect![[r#"
+            $$
+            \begin{align*}
+            \frac{\mathrm{d}}{\mathrm{d}t} A &= (-0.3) A\\
+            \frac{\mathrm{d}}{\mathrm{d}t} B &= 0.5 X\\
+            \frac{\mathrm{d}}{\mathrm{d}t} X &= A + (-2) B
+            \end{align*}
+            $$
+            "#]];
+        expected.assert_eq(&matrix_example().to_latex_string());
```
Comment (georgefst) [inline packages/catlog/src/stdlib/analyses/ode/linear_ode.rs]: Rendered, this produces:

Image

**Comment by epatters** [comment]
Thanks @georgefst and @patrickaldis, this is essentially what I was envisioning! How about you go ahead with the Lotka-Volterra system and then I'll re-review the whole thing?

**Comment by georgefst** [comment]
> Thanks @georgefst and @patrickaldis, this is essentially what I was envisioning! How about you go ahead with the Lotka-Volterra system and then I'll re-review the whole thing?

Great. Yep, working on it now.

**Review by epatters — APPROVED** [review]
